package com.telegram.reporting.dialogs.create_report;

public enum CreateReportState {
    USER_DATE_INPUTTING,
    DATE_VALIDATION,
    USER_DATE_CATEGORY_CHOOSE,
    USER_TIME_INPUTTING,
    TIME_VALIDATION,
    USER_CREATE_ADDITIONAL_REPORT,
    USER_FINAL_REPORT_CONFIRMATION,
    START_DIALOG, END_DIALOG
}
