package com.telegram.reporting.dialogs.general.create_report;

public enum CreateReportState {
    START_CREATE_REPORT_DIALOG,
    USER_DATE_INPUTTING,
    USER_CATEGORY_CHOICE,
    USER_TIME_INPUTTING,
    USER_NOTE_INPUTTING,
    USER_CREATE_ADDITIONAL_REPORT,
    USER_FINAL_REPORT_CONFIRMATION,
    END_CREATE_REPORT_DIALOG
}
