version: '3.1'

services:
  miha_bot:
    container_name: bot
    image: mihaphoenix/telegram_bot:latest
    depends_on:
      - miha-db
    environment:
      BOT_USERNAME: ${BOT_USERNAME}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_DB_USERNAME: ${BOT_DB_USERNAME}
      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
    restart: always
    links:
      - miha-db
  miha-db:
  postgres:
      image: postgres:13.4
      container_name: db
      restart: unless-stopped
      environment:
          - POSTGRES_USER=miha
          - POSTGRES_PASSWORD=miha
          - TZ=Europe/Kiev
      networks:
          net1:
              aliases:
                  - database
networks:
  net1:
