package com.telegram.reporting.dialogs.tariff_dialogs.edit_tariff;

public enum EditTariffEvent {
    RUN_EDIT_TARIFF_DIALOG,

    VALIDATE_USER_DATE_INPUT,
    RETURN_TO_USER_DATE_INPUTTING,
    CHOOSE_TIME_RECORD,
    CHOOSE_EDIT_NOTE,
    CHOOSE_EDIT_CATEGORY,
    CHOOSE_EDIT_SPEND_TIME,
    CONFIRM_EDIT_DATA,
    DECLINE_EDIT_DATA,
    HANDLE_USER_CHANGE_SPEND_TIME,
    HANDLE_USER_CHANGE_CATEGORY,
    HANDLE_USER_CHANGE_NOTE,
    CONFIRM_EDIT_ADDITIONAL_DATA,
    DECLINE_EDIT_ADDITIONAL_DATA,
    CONFIRM_EDIT_ADDITIONAL_TIME_RECORD,
    DECLINE_EDIT_ADDITIONAL_TIME_RECORD,
}