package com.telegram.reporting.dialogs.tariff_dialogs.edit_tariff;

public enum EditTariffState {
    START_EDIT_TARIFF_DIALOG,

    USER_TARIFF_CHOICE,
    USER_EDIT_TARIFF,
    USER_CONFIRM_TARIFF_EDITING,
    USER_DECLINE_TARIFF_EDITING,



    USER_DATE_INPUTTING,
    USER_TIME_RECORD_CHOICE,
    USER_EDIT_DATA_CONFIRMATION,
    USER_EDIT_DATA_CHOICE, USER_CHANGE_NOTE,
    USER_EDIT_ADDITIONAL_DATA,
    USER_EDIT_ADDITIONAL_TIME_RECORD,
    USER_CHANGE_SPEND_TIME,
    USER_CHANGE_CATEGORY,


    END_EDIT_TARIFF_DIALOG
}
