# Application configurations:
spring:
  liquibase:
    change-log: classpath:/migrations/liquibase-changeLog.xml
  date:
    redis:
      repositories:
        enabled: false
  task:
    scheduling:
      pool:
        size: 6
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:postgresql://${BOT_DB_HOST}:${BOT_DB_PORT}/reporting
    driver-class-name: org.postgresql.Driver
    username: ${BOT_DB_USERNAME}
    password: ${BOT_DB_PASSWORD}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  banner:
    location: classpath:META-INF/banner.txt

cache-config:
  caffeine:
    caches:
      - name: employeeStatistic
        capacity: 100
        maxSize: 200
        ttlSecond: 300
#      - name: managerStatistic
#        capacity: 100
#        maxSize: 300
#        ttlSecond: 300

# TelegramBot configurations:
bot:
  username: ${BOT_USERNAME}
  token: ${BOT_TOKEN}

# Tomcat config:
server:
  port: 8008
  tomcat:
    connection-timeout: 20s
    threads:
      max: 100

---

# Dev profile without sslMode
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${BOT_DB_HOST}:${BOT_DB_PORT}/${BOT_DB_NAME}
  task:
    scheduling:
      pool:
        size: 1