package com.telegram.reporting.dialogs.general_dialogs.create_report;

public enum CreateReportEvent {
    RUN_CREATE_REPORT_DIALOG,
    CHOOSE_REPORT_CATEGORY,
    VALIDATE_USER_TIME_INPUT,
    VALIDATE_USER_NOTE_INPUT,
    CONFIRM_ADDITIONAL_REPORT,
    DECLINE_ADDITIONAL_REPORT,
    CONFIRM_CREATION_FINAL_REPORT,
    DECLINE_CREATION_FINAL_REPORT,
    GO_TO_USER_FINAL_REPORT_CONFIRMATION,
    RETURN_TO_USER_DATE_INPUTTING,
    VALIDATE_USER_DATE_INPUT
}