package com.telegram.reporting.dialogs.manager.employee_statistic;

public enum EmployeeStatisticState {
    START_EMPLOYEE_STATISTIC_DIALOG,
    USER_MONTH_INPUTTING,
    USER_EMPLOYEE_CHOOSING,
    USER_LIST_TIME_RECORDS_WATCHING,
    USER_ANOTHER_EMPLOYEE_CHOOSING,
    USER_LOCK_REPORT_STATUS_CHANGING,
    USER_LOCK_REPORT_STATUS_CHOOSING,
    END_EMPLOYEE_STATISTIC_DIALOG
}
