package com.telegram.reporting.dialogs.manager.employee_status;

public enum EmployeeStatusState {
    START_EMPLOYEE_STATUS_DIALOG,
    USER_LIST_EMPLOYEES_CHOOSING,
    USER_EMPLOYEE_CHOOSING,
    USER_EDIT_OPTIONS_CHOOSING,
    USER_EMPLOYEE_ROLE_CHANGING,
    USER_ADDITIONAL_DATA_CHANGING,
    USER_ANOTHER_EMPLOYEE_CHOOSING,
    USER_EMPLOYEE_STATUS_CHANGING,
    END_EMPLOYEE_STATUS_DIALOG
}
