package com.telegram.reporting.dialogs;

public enum ContextVarKey {
    CHAT_ID,
    BUTTON_CALLBACK_VALUE,
    DATE,
    REPORT_TIME,
    REPORT_CATEGORY_TYPE_KEY,
    REPORT_NOTE,
    TIME_RECORDS_JSON,
    TARGET_TIME_RECORD_JSON,
    TIME_RECORD_CHOICE,
    USER_STATUS,
    LOG_PREFIX,
    EMPLOYEE_ORDINAL,
    LIST_EMPLOYEES_JSON,
    TARGET_EMPLOYEE_JSON,
    LOCK_EDIT_REPORT_MESSAGE,
    EXIST_LOCK_EDIT_REPORT,
    PHONE,
}
