package com.telegram.reporting.dialogs;

public enum MessageEvent {
    // create report dialog
    RUN_CREATE_REPORT_DIALOG,
    CHOOSE_REPORT_CATEGORY,
    VALIDATE_USER_TIME_INPUT,
    VALIDATE_USER_NOTE_INPUT,
    CONFIRM_ADDITIONAL_REPORT,
    DECLINE_ADDITIONAL_REPORT,
    CONFIRM_CREATION_FINAL_REPORT,
    DECLINE_CREATION_FINAL_REPORT,

    // delete report dialog
    RUN_DELETE_REPORT_DIALOG,
    CHOOSE_TIME_RECORD,
    CONFIRM_DELETE_TIME_RECORD,
    DECLINE_DELETE_TIME_RECORD,

    // update report dialog
    RUN_UPDATE_REPORT_DIALOG,

    // add new user dialog
    RUN_ADD_NEW_USER_DIALOG,

    //general
    RETURN_TO_USER_DATE_INPUTTING,
    VALIDATE_USER_DATE_INPUT,
}