package com.telegram.reporting.dialogs.manager_dialogs.employee_status;

public enum EmployeeStatusEvent {
    RUN_EMPLOYEE_STATUS_DIALOG,
    HANDLE_USER_CHOICE_LIST,
    HANDLE_EDIT_STATUS_CHOICE,
    HANDLE_EMPLOYEE_STATUS_CHANGE,
    HANDLE_EDIT_ROLE_CHOICE,
    HANDLE_EMPLOYEE_ROLE_CHANGE,
    DECLINE_EMPLOYEE_DATA_CHANGE,
    CONFIRM_EMPLOYEE_ADDITIONAL_DATA_CHANGE,
    DECLINE_EMPLOYEE_ADDITIONAL_DATA_CHANGE,
    RETURN_TO_LIST_EMPLOYEES_CHOICE,
    CHOOSE_ANOTHER_EMPLOYEE,
    CHOOSE_EMPLOYEE,
}