package com.telegram.reporting.dialogs.tariff_dialogs.list_tarrifs;

public enum ListTariffsEvent {
    LIST_TARIFFS_DIALOG_STARTED,
    DISPLAYING_OVERRIDDEN_TARIFFS_CHOSEN,
    DISPLAYING_BY_CATEGORY_CHOSEN,
    DISPLAYING_BY_EMPLOYEE_CHOSEN,
    RESEND_CATEGORY_BUTTONS,
    RESEND_EMPLOYEE_BUTTONS, HANDLING_CHOSEN_EMPLOYEE_TARIFF
}