package com.telegram.reporting.dialogs.tariff_dialogs.list_tarrifs;

public enum ListTariffsState {
    START_LIST_TARIFFS_DIALOG,
    OVERRIDDEN_TARIFF_DISPLAYING_TYPE_CHOICE,
    TARIFF_OPTION_CHOICE,
    TARIFF_CATEGORY_CHOICE,
    TARIFF_EMPLOYEE_CHOICE,
    DISPLAYING_TARIFFS_BY_CATEGORY,
    DISPLAYING_TARIFFS_BY_EMPLOYEE,
    END_LIST_TARIFFS_DIALOG
}